package com.cliptm.socialmedia.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import com.cliptm.socialmedia.data.local.entity.ContentEntity
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

/**
 * Utility for sharing and exporting generated content.
 */
object ShareExportUtil {

    /**
     * Share content as text to any app
     */
    fun shareAsText(context: Context, content: ContentEntity) {
        val text = buildString {
            appendLine(content.textContent)
            if (content.hashtags.isNotEmpty()) {
                appendLine()
                appendLine(content.hashtags.joinToString(" "))
            }
        }
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
            putExtra(Intent.EXTRA_SUBJECT, "Content for ${content.platform}")
        }
        context.startActivity(Intent.createChooser(intent, "Share via"))
    }

    /**
     * Share content directly to a specific platform
     */
    fun shareToApp(context: Context, content: ContentEntity, packageName: String) {
        val text = buildString {
            appendLine(content.textContent)
            if (content.hashtags.isNotEmpty()) appendLine(content.hashtags.joinToString(" "))
        }
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
            setPackage(packageName)
        }
        try { context.startActivity(intent) }
        catch (e: Exception) { shareAsText(context, content) }
    }

    /**
     * Export content list as JSON file
     */
    fun exportAsJson(context: Context, contents: List<ContentEntity>): Uri? {
        val gson = GsonBuilder().setPrettyPrinting().create()
        val json = gson.toJson(contents)
        val fileName = "cliptm_export_${System.currentTimeMillis()}.json"
        val file = File(context.cacheDir, fileName)
        file.writeText(json)
        return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
    }

    /**
     * Export content list as CSV
     */
    fun exportAsCsv(context: Context, contents: List<ContentEntity>): Uri? {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
        val csv = buildString {
            appendLine("ID,Platform,Language,Content Type,Hashtags,Favorite,Created At,Content")
            contents.forEach { c ->
                val escapedContent = c.textContent.replace("\"", "\"\"").replace("\n", " ")
                appendLine("\"${c.id}\",\"${c.platform}\",\"${c.language}\",\"${c.contentType}\",\"${c.hashtags.joinToString(" ")}\",${c.isFavorite},\"${dateFormat.format(Date(c.createdAt))}\",\"$escapedContent\"")
            }
        }
        val fileName = "cliptm_export_${System.currentTimeMillis()}.csv"
        val file = File(context.cacheDir, fileName)
        file.writeText(csv)
        return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
    }

    /**
     * Export single content as formatted text
     */
    fun exportAsFormattedText(content: ContentEntity): String {
        val dateFormat = SimpleDateFormat("dd MMM yyyy HH:mm", Locale.getDefault())
        return buildString {
            appendLine("═══════════════════════════════════════")
            appendLine("ClipTM Social - Generated Content")
            appendLine("═══════════════════════════════════════")
            appendLine("Platform: ${content.platform}")
            appendLine("Language: ${content.language}")
            appendLine("Type: ${content.contentType}")
            appendLine("Date: ${dateFormat.format(Date(content.createdAt))}")
            appendLine("───────────────────────────────────────")
            appendLine()
            appendLine(content.textContent)
            if (content.hashtags.isNotEmpty()) {
                appendLine()
                appendLine("Hashtags: ${content.hashtags.joinToString(" ")}")
            }
            appendLine()
            appendLine("═══════════════════════════════════════")
            appendLine("Generated by ClipTM Social AI")
        }
    }

    /** Platform package names for direct sharing */
    object Packages {
        const val INSTAGRAM = "com.instagram.android"
        const val FACEBOOK = "com.facebook.katana"
        const val TWITTER = "com.twitter.android"
        const val TIKTOK = "com.zhiliaoapp.musically"
        const val LINKEDIN = "com.linkedin.android"
        const val WHATSAPP = "com.whatsapp"
        const val TELEGRAM = "org.telegram.messenger"
    }
}
